# Generated by Django 5.1.5 on 2025-02-12 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreamland_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="gallery_images",
            new_name="gallery_1",
        ),
        migrations.AddField(
            model_name="property",
            name="acre",
            field=models.CharField(
                blank=True,
                help_text="Specify acreage for residential land.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cent",
            field=models.CharField(
                blank=True,
                help_text="Specify cent for residential land.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="gallery_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="properties/images/gallery/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="gallery_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="properties/images/gallery/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_id",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bhk",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="possession_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_status",
            field=models.CharField(
                choices=[("available", "Available"), ("sold", "Sold")],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_subtype",
            field=models.CharField(
                choices=[
                    ("residential_villas/houses", "Residential Villa / Houses"),
                    ("residential_apartments", "Residential Apartment"),
                    ("residential_land", "Residential Land"),
                    ("residential_others", "Residential Other"),
                    ("commercial_shop", "Commercial Shop"),
                    ("commercial_land", "Commercial Land"),
                    ("commercial_building", "Commercial Building"),
                    ("commercial_others", "Commercial Other"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[("residential", "Residential"), ("commercial", "Commercial")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="square_feet",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name="property",
            table="property",
        ),
    ]
