# Generated by Django 5.1.5 on 2025-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreamland_app", "0002_rename_gallery_images_property_gallery_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_location",
            field=models.CharField(max_length=20),
        ),
    ]
