# Generated by Django 5.1.6 on 2025-02-15 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreamland_app", "0003_alter_property_property_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=100, unique=True)),
                (
                    "location_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="locations/images/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "location",
            },
        ),
        migrations.RemoveField(
            model_name="property",
            name="acre",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cent",
        ),
        migrations.AddField(
            model_name="property",
            name="plot_area",
            field=models.CharField(
                blank=True, help_text="Specify the plot area.", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="plot_unit",
            field=models.CharField(
                blank=True,
                choices=[("cent", "Cent"), ("acre", "Acre")],
                help_text="Select unit of plot area.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bhk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="square_feet",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="dreamland_app.location",
            ),
        ),
    ]
