# Generated by Django 5.1.5 on 2025-02-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreamland_app", "0005_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="allocated_locations",
        ),
        migrations.AddField(
            model_name="agent",
            name="allocated_locations",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents_loc",
                to="dreamland_app.location",
            ),
        ),
    ]
