# Generated by Django 5.1.5 on 2025-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreamland_app", "0006_remove_agent_allocated_locations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="allocated_locations",
        ),
        migrations.AlterField(
            model_name="agent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="agent",
            name="allocated_locations",
            field=models.ManyToManyField(
                blank=True, related_name="agents_loc", to="dreamland_app.location"
            ),
        ),
    ]
